# -*- coding: utf-8 -*-
"""Textos do site Sir John's Barbershop: chave -> (ro, en, pt).
O build.py escreve o RO no index.html (e o PT no pt.html) e embute o dicionário no JS para o botão de língua.
Registo romeno: «tu» (barbearia). Diacríticos com vírgula: ș ț."""

T = {
# ---------- meta / globais
'meta.title': ("Sir John's Barbershop · Frizerie în Iași · Costache Negruzzi 1", "Sir John's Barbershop · Barber in Iași · Costache Negruzzi 1", "Sir John's Barbershop · Barbearia em Iași · Costache Negruzzi 1"),
'meta.desc': ("Frizerie pe Strada Costache Negruzzi 1, Iași: tuns, fade, barbă, spălat și styling. 4,8 pe Google din 191 de recenzii. Luni–vineri 10–20, sâmbătă 9–15. Programare pe WhatsApp.",
              "Barbershop on Strada Costache Negruzzi 1, Iași: haircuts, fades, beard, wash and styling. 4.8 on Google from 191 reviews. Mon–Fri 10–20, Sat 9–15. Book on WhatsApp.",
              "Barbearia na Strada Costache Negruzzi 1, Iași: corte, fade, barba, lavagem e styling. 4,8 no Google em 191 avaliações. Seg–sex 10–20, sáb 9–15. Marcação por WhatsApp."),
'faixa': ("PREZENTARE PACHECO STUDIOS · propunere de site pentru Sir John's Barbershop", "PACHECO STUDIOS PREVIEW · website proposal for Sir John's Barbershop", "APRESENTAÇÃO PACHECO STUDIOS · proposta de site para a Sir John's Barbershop"),
'skip': ('Sari la conținut', 'Skip to content', 'Saltar para o conteúdo'),
'tbc': ('de confirmat', 'to be confirmed', 'a confirmar'),
'nav.menu': ('Meniu', 'Menu', 'Menu'),
'nav.acasa': ('Acasă', 'Home', 'Início'),
'nav.servicii': ('Servicii', 'Services', 'Serviços'),
'nav.tunsori': ('Tunsori', 'Cuts', 'Cortes'),
'nav.salonul': ('Salonul', 'The shop', 'A casa'),
'nav.contact': ('Contact', 'Visit', 'Visitar'),
'nav.programare': ('Programează-te', 'Book a chair', 'Marcar'),
'lang.label': ('Limba site-ului', 'Site language', 'Língua do site'),
'cta.suna': ('Sună', 'Call', 'Ligar'),
'cta.wa': ('WhatsApp', 'WhatsApp', 'WhatsApp'),
'wa.salut': ("Salut! Am o întrebare pentru Sir John's:", "Hi! I have a question for Sir John's:", "Olá! Tenho uma pergunta para a Sir John's:"),

# ---------- estado ao vivo
'st.deschis': ('Deschis acum · închide la ', 'Open now · closes at ', 'Aberto agora · fecha às '),
'st.inchis': ('Închis acum · deschide ', 'Closed now · opens ', 'Fechado agora · abre '),
'st.azi': ('azi la ', 'today at ', 'hoje às '),
'st.maine': ('mâine la ', 'tomorrow at ', 'amanhã às '),
'st.zi': (' la ', ' at ', ' às '),

# ---------- início
'h.eyebrow': ('Frizerie · Costache Negruzzi 1 · Iași', 'Barbershop · Costache Negruzzi 1 · Iași', 'Barbearia · Costache Negruzzi 1 · Iași'),
'h.sub': ('Tunsori și bărbi lucrate cu lupa. Un salon cu oglinzi în arcadă, cafea pe masa de lemn și o echipă care se uită de două ori la linia fade-ului.',
          'Cuts and beards done with a magnifying eye. A shop with arched mirrors, coffee on the wooden table and a team that checks the fade line twice.',
          'Cortes e barbas feitos à lupa. Uma casa de espelhos em arco, café na mesa de madeira e uma equipa que olha duas vezes para a linha do fade.'),
'h.cta1': ('Programează-te', 'Book a chair', 'Marcar'),
'h.cta2': ('Vezi tunsorile', 'See the cuts', 'Ver cortes'),
'h.lupa': ('Monoclul lui Sir John: trece peste imagine și o mărește', "Sir John's monocle: it glides over the picture and magnifies it", 'O monóculo de Sir John: passa sobre a imagem e amplia-a'),
'h.lupa.hint': ('Atinge imaginea: monoclul vine după tine', 'Tap the picture: the monocle follows you', 'Toca na imagem: o monóculo vai atrás'),
'h.video': ('Frizerii Sir John’s la lucru', "Sir John's barbers at work", 'Os barbeiros da Sir John’s a trabalhar'),
'h.nota': ('pe Google · 191 de recenzii', 'on Google · 191 reviews', 'no Google · 191 avaliações'),
'mq': ('tuns · fade · barbă · brici · spălat · styling · cafea · Costache Negruzzi 1 · ', 'haircut · fade · beard · razor · wash · styling · coffee · Costache Negruzzi 1 · ', 'corte · fade · barba · navalha · lavagem · styling · café · Costache Negruzzi 1 · '),
'i.kicker': ('Sub monoclu', 'Under the monocle', 'Debaixo do monóculo'),
'i.titlu': ('Linia fade-ului, de aproape', 'The fade line, up close', 'A linha do fade, de perto'),
'i.text': ('Trece monoclul peste tunsoare. Așa ne uităm și noi la ea înainte să te ridici din scaun: tranziția, conturul de la ureche, linia de la ceafă.',
           'Glide the monocle over the cut. That is how we look at it before you get up from the chair: the blend, the line around the ear, the neckline.',
           'Passa o monóculo pelo corte. É assim que olhamos para ele antes de te levantares da cadeira: a transição, o contorno da orelha, a linha da nuca.'),
'i.btn': ('Toate tunsorile', 'All the cuts', 'Todos os cortes'),
's.kicker': ('Ce se face pe scaun', 'What happens in the chair', 'O que se faz na cadeira'),
's.titlu': ('Servicii', 'Services', 'Serviços'),
's.vezi': ('Toate serviciile', 'All services', 'Todos os serviços'),
'r.kicker': ('Ce spun clienții', 'What clients say', 'O que dizem os clientes'),
'r.titlu': ('4,8 din 191 de recenzii', '4.8 from 191 reviews', '4,8 em 191 avaliações'),
'r.cinci': ('dintre ele sunt de 5 stele', 'of them are 5 stars', 'são de 5 estrelas'),
'r.t1': ('Profesioniști și atenți', 'Professional and attentive', 'Profissionais e atentos'),
'r.t1.d': ('Echipa e descrisă ca pricepută și atentă la detalii, cu servicii rapide și bine executate.', 'The team is described as skilled and attentive, with quick, well-executed work.', 'A equipa é descrita como competente e atenta ao detalhe, com serviço rápido e bem executado.'),
'r.t2': ('Diplomele sunt la vedere', 'The diplomas are on the wall', 'Os diplomas estão à vista'),
'r.t2.d': ('Clienții observă certificările echipei expuse în salon — și văd rezultatul pe ceilalți clienți.', 'Clients notice the team’s certificates on display — and see the results on other clients.', 'Os clientes reparam nos certificados da equipa expostos — e veem o resultado nos outros clientes.'),
'r.t3': ('Frizerul recomandat pe nume', 'Barbers recommended by name', 'Barbeiros recomendados pelo nome'),
'r.t3.d': ('Unii clienți își recomandă frizerul pe nume. Și echipa răspunde la recenzii, bune sau mai puțin bune.', 'Some clients recommend their barber by name. And the team answers reviews, good or less good.', 'Alguns clientes recomendam o barbeiro pelo nome. E a equipa responde às avaliações, boas ou menos boas.'),
'v.kicker': ('Unde ne găsești', 'Where to find us', 'Onde estamos'),
'v.titlu': ('Costache Negruzzi 1, bloc H1, scara A, parter', 'Costache Negruzzi 1, block H1, entrance A, ground floor', 'Costache Negruzzi 1, bloco H1, entrada A, rés-do-chão'),
'v.text': ('Caută stâlpul de frizerie roșu-alb-albastru și fațada cu lamele de lemn.', 'Look for the red-white-blue barber pole and the wooden-slat façade.', 'Procura o poste de barbeiro vermelho-branco-azul e a fachada de ripas de madeira.'),
'v.btn': ('Program și hartă', 'Hours and map', 'Horário e mapa'),

# ---------- serviços
'sv.kicker': ('Servicii', 'Services', 'Serviços'),
'sv.titlu': ('Ce poți cere pe scaun', 'What you can ask for', 'O que podes pedir na cadeira'),
'sv.intro': ('Lista exactă și prețurile sunt <span class="tbc">de confirmat</span>. Alege ce vrei, iar la programare primești prețul și durata direct de la frizer.',
             'The exact list and prices are <span class="tbc">to be confirmed</span>. Choose what you want, and you get the price and time straight from the barber when you book.',
             'A lista exata e os preços estão <span class="tbc">a confirmar</span>. Escolhe o que queres e, na marcação, recebes o preço e a duração diretamente do barbeiro.'),
'sv.pret': ('preț', 'price', 'preço'),
'sv.alege': ('Programează', 'Book this', 'Marcar'),
'x.tuns': ('Tuns', 'Haircut', 'Corte'),
'x.tuns.d': ('Fade, clasic sau cu foarfeca. Spui ce vrei, frizerul îți spune ce ți se potrivește.', 'Fade, classic or scissor cut. You say what you want, the barber tells you what suits you.', 'Fade, clássico ou à tesoura. Dizes o que queres, o barbeiro diz-te o que te fica bem.'),
'x.tunsbarba': ('Tuns + barbă', 'Haircut + beard', 'Corte + barba'),
'x.tunsbarba.d': ('Totul într-o singură vizită, cu tranziția dintre păr și barbă lucrată la final.', 'All in one visit, with the hair-to-beard blend finished at the end.', 'Tudo numa visita, com a transição entre cabelo e barba trabalhada no fim.'),
'x.barba': ('Barbă', 'Beard', 'Barba'),
'x.barba.d': ('Formă, lungime și contur curat cu briciul.', 'Shape, length and a clean razor line.', 'Forma, comprimento e contorno limpo à navalha.'),
'x.spalat': ('Spălat și styling', 'Wash and styling', 'Lavagem e styling'),
'x.spalat.d': ('Spălat la chiuvetă, uscat cu foehnul și aranjat cu produs.', 'Washed at the basin, blow-dried and styled with product.', 'Lavado no lavatório, secador e finalizado com produto.'),
'x.fata': ('Îngrijire facială', 'Face care', 'Cuidado de rosto'),
'x.fata.d': ('Un moment de pauză pe scaun, după tuns sau barbă.', 'A pause in the chair, after the cut or beard.', 'Um momento de pausa na cadeira, depois do corte ou da barba.'),
'sv.foto1': ('Spălat la chiuvetă, sub tablourile salonului', 'A wash at the basin, under the shop’s frames', 'Lavagem no lavatório, debaixo dos quadros da casa'),
'sv.foto2': ('Îngrijire facială pe scaun', 'Face care in the chair', 'Cuidado de rosto na cadeira'),
'sv.nu': ('Ai o poză cu tunsoarea pe care o vrei?', 'Got a photo of the cut you want?', 'Tens uma foto do corte que queres?'),
'sv.nu.t': ('Trimite-o pe WhatsApp și îți spunem dacă se potrivește și cât durează.', 'Send it on WhatsApp and we tell you if it works for you and how long it takes.', 'Envia-a por WhatsApp e dizemos-te se resulta e quanto demora.'),
'sv.nu.btn': ('Trimite poza', 'Send the photo', 'Enviar a foto'),
'sv.nu.wa': ('Salut! Vă trimit o poză cu tunsoarea pe care o vreau. Se poate face și cât durează?', 'Hi! I am sending a photo of the cut I want. Can you do it and how long does it take?', 'Olá! Envio uma foto do corte que quero. Dá para fazer e quanto demora?'),

# ---------- tunsori (inspector)
't.kicker': ('Tunsori', 'Cuts', 'Cortes'),
't.titlu': ('Sub monoclu', 'Under the monocle', 'Debaixo do monóculo'),
't.intro': ('Alege o imagine și plimbă monoclul peste ea. Pe telefon, atinge locul pe care vrei să-l vezi de aproape.', 'Pick a picture and move the monocle over it. On a phone, tap the spot you want to see up close.', 'Escolhe uma imagem e passa o monóculo por cima. No telemóvel, toca no sítio que queres ver de perto.'),
't.alege': ('Alege imaginea', 'Choose the picture', 'Escolher imagem'),
't.zoom': ('mărire', 'zoom', 'ampliação'),
't.video': ('Tunsorile în mișcare', 'The cuts in motion', 'Os cortes em movimento'),
't.video.t': ('Câteva fade-uri de la Sir John’s, din profil.', "A few fades from Sir John's, in profile.", 'Alguns fades da Sir John’s, de perfil.'),
't.vreau': ('Întreabă despre asta pe WhatsApp', 'Ask about this on WhatsApp', 'Perguntar por WhatsApp'),
't.wa': ('Salut! Am văzut pe site imaginea „', 'Hi! I saw this picture on your site: “', 'Olá! Vi no site a imagem “'),
't.wa2': ('”. Aș vrea o programare — când aveți loc?', '”. I would like to book — when do you have a free slot?', '”. Queria marcar — quando têm vaga?'),
'c.fade': ('Fade cu linie, profil', 'Fade with a part line, profile', 'Fade com risca, perfil'),
'c.lucru': ('Doi frizeri, două scaune, aceeași atenție', 'Two barbers, two chairs, same care', 'Dois barbeiros, duas cadeiras, a mesma atenção'),
'c.portret': ('Unul dintre frizerii Sir John’s', "One of Sir John's barbers", 'Um dos barbeiros da Sir John’s'),
'c.arcade': ('Oglinzile în arcadă, seara', 'The arched mirrors, at night', 'Os espelhos em arco, à noite'),
'c.spalat': ('Spălat la chiuvetă', 'Wash at the basin', 'Lavagem no lavatório'),
'c.fata': ('Îngrijire facială', 'Face care', 'Cuidado de rosto'),
'c.vitrina': ('Vitrina, cu sigla lui Sir John', "The window, with Sir John's logo", 'A montra, com o logótipo de Sir John'),
'c.interior': ('Salonul: scaune negre, pereți de stuc', 'The shop: black chairs, stucco walls', 'A casa: cadeiras pretas, paredes de estuque'),

# ---------- salonul
'a.kicker': ('Salonul', 'The shop', 'A casa'),
'a.titlu': ('Un gentleman cu ochelari rotunzi, deasupra ușii', 'A gentleman with round glasses, above the door', 'Um cavalheiro de óculos redondos, por cima da porta'),
'a.p1': ('Sir John e omul din siglă: barbă, mustață și ochelari rotunzi. Salonul îi poartă stilul — pereți de stuc gri-lila, oglinzi în arcadă luminate din spate, scaune negre de frizerie și o masă din lemn masiv unde te așteaptă cafeaua.',
         'Sir John is the man in the logo: beard, moustache and round glasses. The shop wears his style — grey-lilac stucco walls, back-lit arched mirrors, black barber chairs and a solid wood table where your coffee waits.',
         'Sir John é o homem do logótipo: barba, bigode e óculos redondos. A casa tem o estilo dele — paredes de estuque cinza-lilás, espelhos em arco iluminados por trás, cadeiras pretas de barbeiro e uma mesa de madeira maciça onde o café te espera.'),
'a.p2': ('Pe perete stau diplomele și certificările echipei. Pe scaun contează un singur lucru: să pleci cu tunsoarea pe care ai cerut-o.',
         'The team’s diplomas and certificates hang on the wall. In the chair only one thing matters: leaving with the cut you asked for.',
         'Na parede estão os diplomas e certificados da equipa. Na cadeira só uma coisa importa: saíres com o corte que pediste.'),
'a.echipa': ('Echipa', 'The team', 'A equipa'),
'a.echipa.t': ('Patru frizeri în cămăși negre. Numele, specializările și programul fiecăruia vor apărea aici.', 'Four barbers in black shirts. Each one’s name, speciality and schedule will appear here.', 'Quatro barbeiros de camisa preta. O nome, a especialidade e o horário de cada um vão aparecer aqui.'),
'a.echipa.alt': ("Echipa Sir John's în salon", "The Sir John's team in the shop", 'A equipa da Sir John’s na casa'),
'a.detalii': ('Detalii pe care le vezi când intri', 'Details you notice when you walk in', 'Detalhes que vês quando entras'),
'a.d1': ('Oglinzile în arcadă', 'The arched mirrors', 'Os espelhos em arco'),
'a.d1.t': ('Luminate din spate. Seara, salonul arată ca o galerie.', 'Back-lit. In the evening the shop looks like a gallery.', 'Iluminados por trás. À noite, a casa parece uma galeria.'),
'a.d2': ('Masa din lemn masiv', 'The solid wood table', 'A mesa de madeira maciça'),
'a.d2.t': ('Cafea, reviste și o tavă cu dulciuri cât aștepți.', 'Coffee, magazines and a tray of sweets while you wait.', 'Café, revistas e uma taça de doces enquanto esperas.'),
'a.d3': ('Programul pe ușă', 'Hours on the door', 'O horário na porta'),
'a.d3.t': ('Luni–vineri 10–20, sâmbătă 9–15, duminică închis.', 'Mon–Fri 10–20, Saturday 9–15, Sunday closed.', 'Seg–sex 10–20, sábado 9–15, domingo fechado.'),
'a.d4': ('Toată lumea e binevenită', 'Everyone is welcome', 'Todos são bem-vindos'),
'a.d4.t': ('Salon prietenos cu comunitatea LGBTQ+.', 'An LGBTQ+ friendly shop.', 'Casa amiga da comunidade LGBTQ+.'),
'a.alt.masa': ('Masa din lemn masiv, cu o cafea', 'The solid wood table, with a coffee', 'A mesa de madeira maciça, com um café'),
'a.alt.usa': ('Ușa salonului, cu sigla și programul', 'The shop door, with the logo and hours', 'A porta da casa, com o logótipo e o horário'),
'a.alt.arcade': ('Oglinzile în arcadă luminate, seara', 'The lit arched mirrors, at night', 'Os espelhos em arco iluminados, à noite'),

# ---------- programare
'b.kicker': ('Programare', 'Booking', 'Marcação'),
'b.titlu': ('Rezervă-ți scaunul', 'Reserve your chair', 'Reserva a tua cadeira'),
'b.intro': ('Serviciul, ziua și ora. Mesajul pleacă gata scris pe WhatsApp, iar frizerul îți confirmă ora.', 'Service, day and time. The message goes out ready on WhatsApp, and the barber confirms your time.', 'Serviço, dia e hora. A mensagem sai pronta por WhatsApp e o barbeiro confirma a hora.'),
'b.pas1': ('Serviciul', 'Service', 'Serviço'),
'b.pas2': ('Ziua', 'Day', 'Dia'),
'b.pas3': ('Ora', 'Time', 'Hora'),
'b.pas4': ('Numele tău', 'Your name', 'O teu nome'),
'b.inchis': ('închis', 'closed', 'fechado'),
'b.zi.nota': ('Luni–vineri 10–20 · sâmbătă 9–15 · duminică închis.', 'Mon–Fri 10–20 · Sat 9–15 · Sunday closed.', 'Seg–sex 10–20 · sáb 9–15 · domingo fechado.'),
'b.ora.gol': ('Alege mai întâi ziua.', 'Choose the day first.', 'Escolhe primeiro o dia.'),
'b.ora.nimic': ('Pentru azi nu mai sunt ore în program. Alege altă zi.', 'No more hours left today. Choose another day.', 'Já não há horas hoje. Escolhe outro dia.'),
'b.nume': ('Numele tău', 'Your name', 'O teu nome'),
'b.frizer': ('Frizer preferat (opțional)', 'Preferred barber (optional)', 'Barbeiro preferido (opcional)'),
'b.frizer.ph': ('ex.: Alin, sau oricine e liber', 'e.g. Alin, or whoever is free', 'ex.: Alin, ou quem estiver livre'),
'b.mesaj': ('Mesajul tău', 'Your message', 'A tua mensagem'),
'b.trimite': ('Trimite pe WhatsApp', 'Send on WhatsApp', 'Enviar por WhatsApp'),
'b.lipsa': ('Mai lipsește: ', 'Still missing: ', 'Falta: '),
'b.lipsa.serv': ('serviciul', 'the service', 'o serviço'),
'b.lipsa.zi': ('ziua', 'the day', 'o dia'),
'b.lipsa.ora': ('ora', 'the time', 'a hora'),
'b.lipsa.nume': ('numele', 'your name', 'o nome'),
'b.gata': ('Gata. Trimite mesajul și așteaptă confirmarea.', 'Done. Send the message and wait for confirmation.', 'Pronto. Envia a mensagem e aguarda confirmação.'),
'b.m.salut': ("Salut! Aș vrea o programare la Sir John's.", "Hi! I would like to book at Sir John's.", 'Olá! Queria marcar na Sir John’s.'),
'b.m.serv': ('Serviciu', 'Service', 'Serviço'),
'b.m.zi': ('Ziua', 'Day', 'Dia'),
'b.m.ora': ('Ora', 'Time', 'Hora'),
'b.m.nume': ('Nume', 'Name', 'Nome'),
'b.m.frizer': ('Frizer preferat', 'Preferred barber', 'Barbeiro preferido'),
'b.m.final': ('Aștept confirmarea. Mulțumesc!', 'Looking forward to your confirmation. Thanks!', 'Fico a aguardar confirmação. Obrigado!'),
'b.m.lipsa': ('(de ales)', '(to choose)', '(por escolher)'),

# ---------- contact
'k.kicker': ('Contact', 'Visit', 'Visitar'),
'k.titlu': ('Stâlpul se învârte, ușa e deschisă', 'The pole is turning, the door is open', 'O poste gira, a porta está aberta'),
'k.adresa': ('Adresa', 'Address', 'Morada'),
'k.adresa.t': ('Strada Costache Negruzzi 1, bloc H1, scara A, parter, 700126 Iași', 'Strada Costache Negruzzi 1, block H1, entrance A, ground floor, 700126 Iași', 'Strada Costache Negruzzi 1, bloco H1, entrada A, rés-do-chão, 700126 Iași'),
'k.telefon': ('Telefon și WhatsApp', 'Phone and WhatsApp', 'Telefone e WhatsApp'),
'k.program': ('Program', 'Opening hours', 'Horário'),
'k.indicatii': ('Indicații de orientare', 'Get directions', 'Obter direções'),
'k.harta': ("Hartă: Sir John's Barbershop, Costache Negruzzi 1, Iași", "Map: Sir John's Barbershop, Costache Negruzzi 1, Iași", "Mapa: Sir John's Barbershop, Costache Negruzzi 1, Iași"),
'k.noapte': ('Seara, cu firma aprinsă', 'In the evening, with the sign lit', 'À noite, com o letreiro aceso'),
'k.parcare': ('Parcare în zonă: <span class="tbc">de confirmat</span>.', 'Parking nearby: <span class="tbc">to be confirmed</span>.', 'Estacionamento: <span class="tbc">a confirmar</span>.'),
'k.inchis': ('Închis', 'Closed', 'Fechado'),

# ---------- dias
'zi.1': ('Luni', 'Monday', 'Segunda'), 'zi.2': ('Marți', 'Tuesday', 'Terça'), 'zi.3': ('Miercuri', 'Wednesday', 'Quarta'),
'zi.4': ('Joi', 'Thursday', 'Quinta'), 'zi.5': ('Vineri', 'Friday', 'Sexta'), 'zi.6': ('Sâmbătă', 'Saturday', 'Sábado'), 'zi.0': ('Duminică', 'Sunday', 'Domingo'),

# ---------- lightbox / rodapé
'lb.inchide': ('Închide', 'Close', 'Fechar'),
'f.tag': ('Frizerie în Iași. Tunsori, bărbi și o cafea pe masa de lemn.', 'Barbershop in Iași. Cuts, beards and a coffee on the wooden table.', 'Barbearia em Iași. Cortes, barbas e um café na mesa de madeira.'),
'f.legal': ('Informații consumatori', 'Consumer information', 'Informação ao consumidor'),
'f.anpc': ('ANPC — Soluționarea alternativă a litigiilor (SAL)', 'ANPC — Alternative dispute resolution (SAL)', 'ANPC — Resolução alternativa de litígios (SAL)'),
'f.odr': ('Soluționarea online a litigiilor (SOL / ODR)', 'Online dispute resolution (ODR)', 'Resolução de litígios em linha (ODR)'),
'f.firma': ('Denumire firmă și CUI: <span class="tbc">de confirmat</span>', 'Company name and tax ID: <span class="tbc">to be confirmed</span>', 'Denominação e CUI: <span class="tbc">a confirmar</span>'),
'f.facut': ('Site realizat de Pacheco Studios', 'Website by Pacheco Studios', 'Site feito pela Pacheco Studios'),
'nojs': ("Sir John's Barbershop · Str. Costache Negruzzi 1, bl. H1, sc. A, parter, 700126 Iași · +40 731 422 775 · luni–vineri 10–20, sâmbătă 9–15, duminică închis.", '', ''),
}
