# -*- coding: utf-8 -*-
"""Textos do site Beauty Zone: chave -> (ro, en, pt).
O build.py escreve o RO no index.html (e o PT no pt.html) e embute o dicionário no JS para o botão de língua.
Registo romeno: «tu» (salão jovem). Diacríticos com vírgula: ș ț."""

T = {
# ---------- meta / globais
'meta.title': ('Beauty Zone · Unghii, gene, sprâncene și machiaj · Strada Armeană 11, Iași',
               'Beauty Zone · Nails, lashes, brows & make-up · Strada Armeană 11, Iași',
               'Beauty Zone · Unhas, pestanas, sobrancelhas e maquilhagem · Strada Armeană 11, Iași'),
'meta.desc': ('Salon de înfrumusețare pe Strada Armeană 11, Iași: manichiură, nail art, extensii de gene, sprâncene și machiaj. 5,0 pe Google. Programare pe WhatsApp.',
              'Beauty salon on Strada Armeană 11, Iași: manicure, nail art, lash extensions, brows and make-up. 5.0 on Google. Book on WhatsApp.',
              'Salão de beleza na Strada Armeană 11, Iași: manicure, nail art, extensões de pestanas, sobrancelhas e maquilhagem. 5,0 no Google. Marcação por WhatsApp.'),
'faixa': ('PREZENTARE PACHECO STUDIOS · propunere de site pentru Beauty Zone',
          'PACHECO STUDIOS PREVIEW · website proposal for Beauty Zone',
          'APRESENTAÇÃO PACHECO STUDIOS · proposta de site para o Beauty Zone'),
'skip': ('Sari la conținut', 'Skip to content', 'Saltar para o conteúdo'),
'tbc': ('de confirmat', 'to be confirmed', 'a confirmar'),
'nav.menu': ('Meniu', 'Menu', 'Menu'),
'nav.acasa': ('Acasă', 'Home', 'Início'),
'nav.servicii': ('Servicii', 'Services', 'Serviços'),
'nav.lucrari': ('Lucrări', 'Our work', 'Trabalhos'),
'nav.salonul': ('Salonul', 'The salon', 'O salão'),
'nav.contact': ('Contact', 'Visit', 'Visitar'),
'nav.programare': ('Programează-te', 'Book now', 'Marcar'),
'lang.label': ('Limba site-ului', 'Site language', 'Língua do site'),
'cta.suna': ('Sună', 'Call', 'Ligar'),
'cta.wa': ('WhatsApp', 'WhatsApp', 'WhatsApp'),
'wa.salut': ('Bună! Am o întrebare pentru Beauty Zone:', 'Hi! I have a question for Beauty Zone:', 'Olá! Tenho uma pergunta para o Beauty Zone:'),

# ---------- início
'h.eyebrow': ('Salon de înfrumusețare · Strada Armeană 11, Iași', 'Beauty salon · Strada Armeană 11, Iași', 'Salão de beleza · Strada Armeană 11, Iași'),
'h.sub': ('Unghii, gene, sprâncene și machiaj, lucrate în lumina bună a oglinzii. În centrul vechi al Iașului.',
          'Nails, lashes, brows and make-up, done in the good light of the mirror. In the old centre of Iași.',
          'Unhas, pestanas, sobrancelhas e maquilhagem, feitas na boa luz do espelho. No centro antigo de Iași.'),
'h.ruj': ('hai la oglindă', 'come to the mirror', 'vem ao espelho'),
'h.cta1': ('Alege tratamentul', 'Choose a treatment', 'Escolher tratamento'),
'h.cta2': ('Vezi lucrările', 'See our work', 'Ver trabalhos'),
'h.nota': ('pe Google', 'on Google', 'no Google'),
'h.oglinda': ('Oglinda salonului: unghii cu sclipici roz, reflectate în oglindă', 'The salon mirror: pink glitter nails, reflected', 'O espelho do salão: unhas com brilho rosa, refletidas'),
'h.scroll': ('Ce facem', 'What we do', 'O que fazemos'),
'mq': ('manichiură · nail art · construcție cu gel · extensii de gene · sprâncene · machiaj · Strada Armeană 11 ·',
       'manicure · nail art · gel extensions · lash extensions · brows · make-up · Strada Armeană 11 ·',
       'manicure · nail art · gel · extensões de pestanas · sobrancelhas · maquilhagem · Strada Armeană 11 ·'),
'd.kicker': ('Patru lucruri, la aceeași oglindă', 'Four things, at the same mirror', 'Quatro coisas, no mesmo espelho'),
'd.titlu': ('Ce facem la Beauty Zone', 'What we do at Beauty Zone', 'O que fazemos no Beauty Zone'),
'd.unghii': ('Unghii', 'Nails', 'Unhas'),
'd.unghii.t': ('De la scurte și curate la migdală lungă sau stiletto. Construcție, întreținere și nail art: linii, folie, strasuri.',
               'From short and clean to long almond or stiletto. Extensions, infills and nail art: lines, foil, rhinestones.',
               'De curtas e limpas a amêndoa comprida ou stiletto. Construção, manutenção e nail art: linhas, folha, strass.'),
'd.gene': ('Gene', 'Lashes', 'Pestanas'),
'd.gene.t': ('Extensii cu volum sau o curbură care deschide privirea, fără rimel.',
             'Volume extensions, or a curl that opens up your eyes without mascara.',
             'Extensões com volume, ou uma curvatura que abre o olhar sem rímel.'),
'd.sprancene': ('Sprâncene', 'Brows', 'Sobrancelhas'),
'd.sprancene.t': ('O formă gândită pentru fața ta, cu firul pus în ordine.',
                  'A shape made for your face, every hair put in order.',
                  'Uma forma pensada para o teu rosto, com cada pelo no sítio.'),
'd.machiaj': ('Machiaj', 'Make-up', 'Maquilhagem'),
'd.machiaj.t': ('Pentru o seară, o nuntă sau o ședință foto. Pleoapă lucrată, ten luminos.',
                'For a night out, a wedding or a photo shoot. Detailed eyes, glowing skin.',
                'Para uma noite, um casamento ou uma sessão fotográfica. Olhos trabalhados, pele luminosa.'),
'd.vezi': ('Vezi serviciile', 'See the services', 'Ver serviços'),
'l.kicker': ('Din ultimele lucrări', 'Recent work', 'Trabalhos recentes'),
'l.titlu': ('Mâini și priviri care au trecut pe la noi', 'Hands and eyes that passed through our chair', 'Mãos e olhares que passaram por cá'),
'l.toate': ('Toate lucrările', 'All our work', 'Todos os trabalhos'),
'p.kicker': ('Programare în patru pași', 'Book in four steps', 'Marcação em quatro passos'),
'p.titlu': ('Alegi tratamentul, ziua și ora. Mesajul pleacă gata scris.', 'Pick the treatment, the day and the time. The message is written for you.', 'Escolhes o tratamento, o dia e a hora. A mensagem sai já escrita.'),
'p.text': ('Fiecare pas aprinde un bec. Când sunt toate aprinse, trimiți mesajul pe WhatsApp și îți confirmăm ora.',
           'Each step lights a bulb. When they are all on, you send the message on WhatsApp and we confirm your time.',
           'Cada passo acende uma lâmpada. Quando estão todas acesas, envias a mensagem por WhatsApp e confirmamos a hora.'),
'p.btn': ('Începe programarea', 'Start booking', 'Começar marcação'),
'v.kicker': ('Ne găsești ușor', 'Easy to find', 'Fácil de encontrar'),
'v.titlu': ('Strada Armeană 11, în centrul vechi', 'Strada Armeană 11, in the old centre', 'Strada Armeană 11, no centro antigo'),
'v.nota': ('5,0 pe Google', '5.0 on Google', '5,0 no Google'),
'v.nota.t': ('Nota maximă, de la cei care ne-au lăsat o recenzie. Le găsești pe hartă, la Beauty Zone.',
             'Top marks from everyone who left a review. You can read them on the map, under Beauty Zone.',
             'Nota máxima, de quem deixou avaliação. Estão no mapa, em Beauty Zone.'),
'v.harta': ('Deschide în Google Maps', 'Open in Google Maps', 'Abrir no Google Maps'),
'v.program': ('Vezi programul', 'See opening hours', 'Ver horário'),

# ---------- serviços
's.kicker': ('Servicii', 'Services', 'Serviços'),
's.titlu': ('Ce poți programa', 'What you can book', 'O que podes marcar'),
's.intro': ('Patru capitole, fiecare cu lucrările lui. Lista exactă de tratamente și prețurile sunt <span class="tbc">de confirmat</span> — până atunci, întreabă-ne pe WhatsApp și primești răspunsul direct.',
            'Four chapters, each with its own work. The exact treatment list and prices are <span class="tbc">to be confirmed</span> — until then, ask us on WhatsApp and get a direct answer.',
            'Quatro capítulos, cada um com os seus trabalhos. A lista exata de tratamentos e os preços estão <span class="tbc">a confirmar</span> — até lá, pergunta-nos por WhatsApp e recebes resposta direta.'),
's.alege': ('Programează', 'Book this', 'Marcar'),
's.pret': ('preț', 'price', 'preço'),
'u.constructie': ('Construcție cu gel', 'Gel extensions', 'Construção em gel'),
'u.constructie.d': ('Lungime și formă noi: migdală, pătrat, stiletto.', 'New length and shape: almond, square, stiletto.', 'Comprimento e forma novos: amêndoa, quadrada, stiletto.'),
'u.intretinere': ('Întreținere', 'Infill', 'Manutenção'),
'u.intretinere.d': ('Pentru unghiile deja construite, când a crescut unghia naturală.', 'For existing extensions, once the natural nail has grown.', 'Para unhas já construídas, quando a unha natural cresceu.'),
'u.semi': ('Manichiură semipermanentă', 'Gel polish manicure', 'Manicure gelinho'),
'u.semi.d': ('Unghia ta naturală, scurtă și curată, cu culoare care ține.', 'Your natural nail, short and clean, with colour that lasts.', 'A tua unha natural, curta e limpa, com cor que dura.'),
'u.art': ('Nail art', 'Nail art', 'Nail art'),
'u.art.d': ('French, linii grafice, folie, strasuri, desen pe o unghie sau pe toate.', 'French, graphic lines, foil, rhinestones, on one nail or all of them.', 'Francesa, linhas gráficas, folha, strass, numa unha ou em todas.'),
'g.extensii': ('Extensii de gene', 'Lash extensions', 'Extensões de pestanas'),
'g.extensii.d': ('Volum și lungime, alese după forma ochiului.', 'Volume and length, chosen for your eye shape.', 'Volume e comprimento, escolhidos para a forma do olho.'),
'g.lift': ('Lifting de gene', 'Lash lift', 'Lifting de pestanas'),
'g.lift.d': ('Genele tale, curbate și puse în valoare.', 'Your own lashes, curled and defined.', 'As tuas pestanas, curvadas e realçadas.'),
'b.stil': ('Stilizare sprâncene', 'Brow shaping', 'Design de sobrancelhas'),
'b.stil.d': ('Formă, simetrie și fir ordonat.', 'Shape, symmetry and tidy hairs.', 'Forma, simetria e pelos arrumados.'),
'm.zi': ('Machiaj de zi sau de seară', 'Day or evening make-up', 'Maquilhagem de dia ou de noite'),
'm.zi.d': ('Ten luminos, privire definită, rezistent toată ziua.', 'Glowing skin, defined eyes, lasts all day.', 'Pele luminosa, olhar definido, dura o dia todo.'),
'm.eveniment': ('Machiaj pentru evenimente și ședințe foto', 'Make-up for events and photo shoots', 'Maquilhagem para eventos e sessões fotográficas'),
'm.eveniment.d': ('Nunți, botezuri, absolviri, studio. Spune-ne data din timp.', 'Weddings, christenings, graduations, studio. Tell us the date early.', 'Casamentos, batizados, finalistas, estúdio. Diz-nos a data com antecedência.'),
's.nu.titlu': ('Nu știi ce să alegi?', 'Not sure what to choose?', 'Não sabes o que escolher?'),
's.nu.text': ('Trimite-ne o poză cu ce îți place și îți spunem ce tratament e și cât durează.', 'Send us a photo of what you like and we will tell you which treatment it is and how long it takes.', 'Envia-nos uma foto do que gostas e dizemos-te que tratamento é e quanto demora.'),
's.nu.btn': ('Trimite o poză pe WhatsApp', 'Send a photo on WhatsApp', 'Enviar foto por WhatsApp'),
's.nu.wa': ('Bună! Vă trimit o poză cu ce mi-ar plăcea. Ce tratament ar fi și cât durează?', 'Hi! I am sending a photo of what I would like. Which treatment is it and how long does it take?', 'Olá! Envio uma foto do que gostava. Que tratamento é e quanto demora?'),

# ---------- trabalhos
'g.kicker': ('Lucrări', 'Our work', 'Trabalhos'),
'g.titlu': ('Din oglinda noastră', 'From our mirror', 'Do nosso espelho'),
'g.intro': ('Lucrări făcute la Beauty Zone. Atinge o fotografie ca s-o vezi mare.', 'Work done at Beauty Zone. Tap a photo to see it full size.', 'Trabalhos feitos no Beauty Zone. Toca numa foto para a ver em grande.'),
'g.filtru': ('Filtrează lucrările', 'Filter the work', 'Filtrar trabalhos'),
'g.toate': ('Toate', 'All', 'Todos'),
'g.vreau': ('Vreau și eu asta', 'I want this too', 'Também quero isto'),
'g.wa1': ('Bună! Aș vrea și eu lucrarea de pe site: ', 'Hi! I would like this one from your website: ', 'Olá! Também queria este trabalho do site: '),
'g.wa2': ('. Când ai un loc liber?', '. When do you have a free slot?', '. Quando tens vaga?'),
'h.becuri': ('Becurile oglinzii', 'Mirror bulbs', 'Lâmpadas do espelho'),
'lb.inchide': ('Închide', 'Close', 'Fechar'),
'lb.prev': ('Fotografia anterioară', 'Previous photo', 'Foto anterior'),
'lb.next': ('Fotografia următoare', 'Next photo', 'Foto seguinte'),
'c.sclipici': ('Migdală lungă, sclipici roz', 'Long almond, pink glitter', 'Amêndoa comprida, brilho rosa'),
'c.migdala': ('Migdală nude cu folie irizată', 'Nude almond with iridescent foil', 'Amêndoa nude com folha iridescente'),
'c.perle': ('Nude lăptos, perle verzi și folie argintie', 'Milky nude, green beads and silver foil', 'Nude leitoso, pérolas verdes e folha prateada'),
'c.linii': ('Scurte, cu linii grafice alb-negru', 'Short, with black and white graphic lines', 'Curtas, com linhas gráficas preto e branco'),
'c.negre': ('Negru lucios, formă pătrată', 'Glossy black, square shape', 'Preto brilhante, forma quadrada'),
'c.inimioara': ('Roz perlat cu inimioară din strasuri', 'Pearly pink with a rhinestone heart', 'Rosa perolado com coração de strass'),
'c.mate': ('Mat, albastru și portocaliu în diagonală', 'Matte, blue and orange on the diagonal', 'Mate, azul e laranja na diagonal'),
'c.floare': ('Roz pudrat cu o floare pe inelar', 'Powder pink with a flower on the ring finger', 'Rosa pó com uma flor no anelar'),
'c.privire': ('Gene curbate, privire deschisă', 'Curled lashes, open eyes', 'Pestanas curvadas, olhar aberto'),
'c.extensii': ('Extensii de gene cu volum', 'Volume lash extensions', 'Extensões de pestanas com volume'),
'c.sprancene': ('Sprâncene stilizate', 'Shaped brows', 'Sobrancelhas desenhadas'),
'c.machiaj': ('Pleoapă în nuanțe calde, gene bogate', 'Warm-toned lids, full lashes', 'Pálpebra em tons quentes, pestanas cheias'),

# ---------- o salão
'a.kicker': ('Salonul', 'The salon', 'O salão'),
'a.titlu': ('Un salon mic pe Armeană, cu lumina pusă unde trebuie', 'A small salon on Armeană, with the light exactly where it should be', 'Um salão pequeno na Armeană, com a luz onde deve estar'),
'a.p1': ('Beauty Zone e pe Strada Armeană 11, în centrul Iașului, pe aceeași stradă cu Biserica Armenească. Aici se lucrează unghii, gene, sprâncene și machiaj — iar fotografiile de pe acest site sunt lucrări făcute chiar aici.',
         'Beauty Zone is at Strada Armeană 11, in central Iași, on the same street as the Armenian Church. We do nails, lashes, brows and make-up — and the photos on this site are work done right here.',
         'O Beauty Zone fica na Strada Armeană 11, no centro de Iași, na mesma rua da Igreja Arménia. Aqui fazem-se unhas, pestanas, sobrancelhas e maquilhagem — e as fotografias deste site são trabalhos feitos aqui mesmo.'),
'a.p2': ('Oglinda e locul în care se vede totul: forma unghiei, curbura genei, simetria sprâncenei. De aceea lucrăm cu lumină bună și fără grabă.',
         'The mirror is where everything shows: the shape of a nail, the curl of a lash, the symmetry of a brow. That is why we work in good light and without rushing.',
         'O espelho é onde tudo se vê: a forma da unha, a curvatura da pestana, a simetria da sobrancelha. Por isso trabalhamos com boa luz e sem pressa.'),
'a.pasi': ('Cum decurge o programare', 'How a booking works', 'Como funciona uma marcação'),
'a.pas1': ('Alegi tratamentul', 'Choose the treatment', 'Escolhes o tratamento'),
'a.pas1.t': ('Pe site sau ne trimiți o poză cu ce îți place.', 'On the site, or send us a photo of what you like.', 'No site, ou envias-nos uma foto do que gostas.'),
'a.pas2': ('Propui ziua și ora', 'Suggest a day and time', 'Propões o dia e a hora'),
'a.pas2.t': ('Mesajul pleacă gata scris pe WhatsApp.', 'The message goes out ready-written on WhatsApp.', 'A mensagem sai já escrita por WhatsApp.'),
'a.pas3': ('Îți confirmăm ora', 'We confirm your time', 'Confirmamos a hora'),
'a.pas3.t': ('Primești răspunsul pe același fir.', 'You get the answer in the same chat.', 'Recebes a resposta na mesma conversa.'),
'a.pas4': ('Vii pe Armeană 11', 'Come to Armeană 11', 'Vens à Armeană 11'),
'a.pas4.t': ('Restul se întâmplă la oglindă.', 'The rest happens at the mirror.', 'O resto acontece ao espelho.'),
'a.echipa': ('Echipa', 'The team', 'A equipa'),
'a.echipa.t': ('Numele, specializările și fotografiile echipei vor apărea aici.', 'The team’s names, specialities and photos will appear here.', 'Os nomes, especialidades e fotos da equipa vão aparecer aqui.'),
'a.faq': ('Întrebări de la prima vizită', 'First-visit questions', 'Perguntas da primeira visita'),
'a.q1': ('Cât costă?', 'How much does it cost?', 'Quanto custa?'),
'a.r1': ('Lista de prețuri e <span class="tbc">de confirmat</span>. Scrie-ne pe WhatsApp ce tratament vrei și primești prețul exact.', 'The price list is <span class="tbc">to be confirmed</span>. Message us on WhatsApp with the treatment you want and get the exact price.', 'A tabela de preços está <span class="tbc">a confirmar</span>. Escreve-nos por WhatsApp com o tratamento que queres e recebes o preço exato.'),
'a.q2': ('Cât durează?', 'How long does it take?', 'Quanto tempo demora?'),
'a.r2': ('Depinde de tratament și de ce ai deja (de exemplu, o întreținere e mai scurtă decât o construcție nouă). Îți spunem durata când confirmăm ora.', 'It depends on the treatment and what you already have (an infill is shorter than a new set, for example). We tell you the duration when we confirm.', 'Depende do tratamento e do que já tens (uma manutenção é mais curta do que uma construção nova, por exemplo). Dizemos-te a duração quando confirmamos a hora.'),
'a.q3': ('Pot veni fără programare?', 'Can I walk in?', 'Posso ir sem marcação?'),
'a.r3': ('Cel mai sigur e să scrii înainte, ca să te așteptăm cu locul liber. Disponibilitatea fără programare e <span class="tbc">de confirmat</span>.', 'It is safest to message first so your chair is free. Walk-in availability is <span class="tbc">to be confirmed</span>.', 'O mais seguro é escrever antes, para te esperarmos com o lugar livre. A disponibilidade sem marcação está <span class="tbc">a confirmar</span>.'),

# ---------- marcação
'b.kicker': ('Programare', 'Booking', 'Marcação'),
'b.titlu': ('Aprinde toate becurile', 'Light up all the bulbs', 'Acende todas as lâmpadas'),
'b.intro': ('Patru pași. La final, mesajul pleacă gata scris pe WhatsApp, iar noi îți confirmăm ora.', 'Four steps. At the end the message goes out ready on WhatsApp, and we confirm your time.', 'Quatro passos. No fim, a mensagem sai pronta por WhatsApp e nós confirmamos a hora.'),
'b.pas1': ('Ce tratament?', 'Which treatment?', 'Que tratamento?'),
'b.pas2': ('În ce zi?', 'Which day?', 'Que dia?'),
'b.pas3': ('La ce oră?', 'What time?', 'A que horas?'),
'b.pas4': ('Cum te cheamă?', 'Your name?', 'Como te chamas?'),
'b.zi.nota': ('Programul pe fiecare zi e <span class="tbc">de confirmat</span>; marțea suntem deschiși 10–20. Îți confirmăm pe WhatsApp.', 'Opening hours for each day are <span class="tbc">to be confirmed</span>; on Tuesdays we are open 10–20. We confirm on WhatsApp.', 'O horário de cada dia está <span class="tbc">a confirmar</span>; à terça estamos abertos das 10 às 20. Confirmamos por WhatsApp.'),
'b.oricand': ('Oricând', 'Any time', 'Qualquer hora'),
'b.nume': ('Numele tău', 'Your name', 'O teu nome'),
'b.nota': ('Ceva de știut? (opțional)', 'Anything we should know? (optional)', 'Algo que devamos saber? (opcional)'),
'b.nota.ph': ('ex.: am deja unghii construite, e prima vizită', 'e.g. I already have extensions, it is my first visit', 'ex.: já tenho unhas de gel, é a primeira visita'),
'b.mesaj': ('Mesajul tău', 'Your message', 'A tua mensagem'),
'b.trimite': ('Trimite pe WhatsApp', 'Send on WhatsApp', 'Enviar por WhatsApp'),
'b.lipsa': ('Mai aprinde un bec: ', 'Light one more bulb: ', 'Falta acender: '),
'b.lipsa.trat': ('alege tratamentul', 'choose the treatment', 'escolhe o tratamento'),
'b.lipsa.zi': ('alege ziua', 'choose the day', 'escolhe o dia'),
'b.lipsa.ora': ('alege ora', 'choose the time', 'escolhe a hora'),
'b.lipsa.nume': ('scrie-ți numele', 'write your name', 'escreve o teu nome'),
'b.gata': ('Toate becurile sunt aprinse. Trimite mesajul.', 'All bulbs are on. Send the message.', 'Todas as lâmpadas acesas. Envia a mensagem.'),
'b.m.salut': ('Bună! Aș vrea o programare la Beauty Zone.', 'Hi! I would like to book at Beauty Zone.', 'Olá! Queria marcar no Beauty Zone.'),
'b.m.trat': ('Tratament', 'Treatment', 'Tratamento'),
'b.m.zi': ('Ziua', 'Day', 'Dia'),
'b.m.ora': ('Ora', 'Time', 'Hora'),
'b.m.nume': ('Nume', 'Name', 'Nome'),
'b.m.nota': ('Notă', 'Note', 'Nota'),
'b.m.final': ('Aștept confirmarea. Mulțumesc!', 'Looking forward to your confirmation. Thank you!', 'Fico a aguardar confirmação. Obrigada!'),
'b.m.lipsa': ('(de ales)', '(to choose)', '(por escolher)'),
'b.m.oricand': ('oricând îmi propuneți', 'whenever suits you', 'quando vos der jeito'),
'b.becuri': ('Becuri aprinse', 'Bulbs lit', 'Lâmpadas acesas'),

# ---------- visitar
'v2.kicker': ('Contact', 'Visit', 'Visitar'),
'v2.titlu': ('Te așteptăm pe Armeană', 'See you on Armeană', 'Esperamos-te na Armeană'),
'v2.adresa': ('Adresa', 'Address', 'Morada'),
'v2.telefon': ('Telefon și WhatsApp', 'Phone and WhatsApp', 'Telefone e WhatsApp'),
'v2.program': ('Program', 'Opening hours', 'Horário'),
'v2.azi': ('Marți, oră cu oră', 'Tuesday, hour by hour', 'Terça, hora a hora'),
'v2.azi.t': ('Becurile aprinse sunt orele deja trecute din ziua de marți.', 'The lit bulbs are the hours already gone on a Tuesday.', 'As lâmpadas acesas são as horas já passadas numa terça.'),
'v2.deschis': ('Deschis acum', 'Open now', 'Aberto agora'),
'v2.inchis': ('Acum închis', 'Closed now', 'Fechado agora'),
'v2.necunoscut': ('Programul de azi e de confirmat', 'Today’s hours are to be confirmed', 'O horário de hoje está a confirmar'),
'v2.harta': ('Hartă: Beauty Zone, Strada Armeană 11, Iași', 'Map: Beauty Zone, Strada Armeană 11, Iași', 'Mapa: Beauty Zone, Strada Armeană 11, Iași'),
'v2.cum': ('Cum ajungi', 'Getting here', 'Como chegar'),
'v2.cum.t': ('Pe aceeași stradă cu Biserica Armenească, cod poștal 700039. Parcare în zonă: <span class="tbc">de confirmat</span>.', 'On the same street as the Armenian Church, postcode 700039. Parking nearby: <span class="tbc">to be confirmed</span>.', 'Na mesma rua da Igreja Arménia, código postal 700039. Estacionamento: <span class="tbc">a confirmar</span>.'),
'v2.indicatii': ('Indicații de orientare', 'Get directions', 'Obter direções'),

# ---------- zile
'zi.1': ('Luni', 'Monday', 'Segunda'), 'zi.2': ('Marți', 'Tuesday', 'Terça'), 'zi.3': ('Miercuri', 'Wednesday', 'Quarta'),
'zi.4': ('Joi', 'Thursday', 'Quinta'), 'zi.5': ('Vineri', 'Friday', 'Sexta'), 'zi.6': ('Sâmbătă', 'Saturday', 'Sábado'), 'zi.0': ('Duminică', 'Sunday', 'Domingo'),

# ---------- rodapé
'f.tag': ('Unghii, gene, sprâncene și machiaj în centrul vechi al Iașului.', 'Nails, lashes, brows and make-up in the old centre of Iași.', 'Unhas, pestanas, sobrancelhas e maquilhagem no centro antigo de Iași.'),
'f.legal': ('Informații consumatori', 'Consumer information', 'Informação ao consumidor'),
'f.anpc': ('ANPC — Soluționarea alternativă a litigiilor (SAL)', 'ANPC — Alternative dispute resolution (SAL)', 'ANPC — Resolução alternativa de litígios (SAL)'),
'f.odr': ('Soluționarea online a litigiilor (SOL / ODR)', 'Online dispute resolution (ODR)', 'Resolução de litígios em linha (ODR)'),
'f.firma': ('Denumire firmă și CUI: <span class="tbc">de confirmat</span>', 'Company name and tax ID: <span class="tbc">to be confirmed</span>', 'Denominação e CUI: <span class="tbc">a confirmar</span>'),
'f.facut': ('Site realizat de Pacheco Studios', 'Website by Pacheco Studios', 'Site feito pela Pacheco Studios'),
'nojs': ('Beauty Zone · Strada Armeană 11, 700039 Iași · +40 729 376 681 · marți 10–20 (restul programului de confirmat).', '', ''),
}
